-- ================================================================
--  Add reg_id column to all event registration tables
--  Format:
--    VYG-1XXXX  -> innovation_college_registrations
--    VYG-2XXXX  -> talent_nominations (talent-student)
--    VYG-3XXXX  -> talent_nominations (talent-combined / parent)
--    VYG-4XXXX  -> shortfilm_registrations
--
--  reg_id is generated by the backend (Node.js) at insert time.
--  It is stored as a UNIQUE TEXT column so it can be displayed
--  to users instead of the raw UUID.
-- ================================================================

ALTER TABLE innovation_college_registrations
  ADD COLUMN IF NOT EXISTS reg_id TEXT UNIQUE;

ALTER TABLE talent_nominations
  ADD COLUMN IF NOT EXISTS reg_id TEXT UNIQUE;

ALTER TABLE shortfilm_registrations
  ADD COLUMN IF NOT EXISTS reg_id TEXT UNIQUE;

-- Index for fast lookups by reg_id
CREATE INDEX IF NOT EXISTS idx_innov_college_reg_id
  ON innovation_college_registrations (reg_id);

CREATE INDEX IF NOT EXISTS idx_talent_nominations_reg_id
  ON talent_nominations (reg_id);

CREATE INDEX IF NOT EXISTS idx_shortfilm_reg_id
  ON shortfilm_registrations (reg_id);
